
version: '2'

services:
  meanstack:
    image: meanstack:latest
    build:
      context: .
      dockerfile: dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 server.js
